defmodule PhoenixHelpdesk.Support.Ticket do
  # Using Ash.Resource here turns this model into an Ash resource.
  use Ash.Resource,
    # Tells ash you want this resource to store its data in postgres.
    data_layer: AshPostgres.DataLayer

  # The postgres keyword is specific to the AshPostgres module.
  # It tells postgres what to call the table and to
  # communicate with postgres through PhoenixHelpdesk.Repo
  postgres do
    # Tells postgres what to call the table
    table "tickets"
    # Tells Ash how to interface with the postgres table
    repo PhoenixHelpdesk.Repo
  end

  actions do
    # exposes default built in actions to modify the resource
    defaults [:create, :read, :update, :destroy]

    # This is a custom create action which only accepts the subject parameter.
    # By default you can provide all public attributes to an action
    create :open do
      accept [:subject]
    end

    # This is a custom update action which accepts no parameters.
    update :close do
      # We don't want to accept any input here
      accept []

      # sets the attribute `:status` to `:closed`
      change set_attribute(:status, :closed)
    end

    update :assign do
      # No attributes should be accepted
      accept []

      # We accept a representative's id as input here
      argument :representative_id, :uuid do
        # This action requires representative_id
        allow_nil? false
      end

      # We use a change here to replace the related Representative
      # If there is a different representative for this Ticket, it will be changed to the new one
      # The Representative itself is not modified in any way
      change manage_relationship(:representative_id, :representative, type: :append_and_remove)
    end
  end

  # Attributes are the simple pieces of data that exist on your resource
  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id
    # Add a string type attribute called `:subject`
    attribute :subject, :string do
      # We don't want subject to ever be `nil`
      allow_nil? false
    end

    # status is either `open` or `closed`.
    attribute :status, :atom do
      # Constraints allow you to provide extra rules for the value.
      # The available constraints depend on the type
      # See the documentation for each type to know what constraints are available
      # Since atoms are generally only used when we know all of the values
      # it provides a `one_of` constraint, that only allows those values
      constraints one_of: [:open, :closed]

      # The status defaulting to open makes sense
      default :open
      # We also don't want status to ever be `nil`
      allow_nil? false
    end
  end

  relationships do
    # belongs_to means that the destination attribute is unique, meaning only one related record could exist.
    # We assume that the destination attribute is `representative_id` based
    # on the name of this relationship and that the source attribute is `representative_id`.
    # We create `representative_id` automatically.
    belongs_to :representative, PhoenixHelpdesk.Support.Representative
  end
end
